### ISSUE TITLE
cant activate carplay

### ISSUE THREAD

**Issue by adandashi** [jilleb/mib1-toolbox#12]
when i try to enable the carplay from the green menu it asks me to run the aio patch first but when running that i get the attached message-check screen shots-It also says that the carplay and android auto is activated but i cant access it, can anyone help ?

![WhatsApp Image 2024-03-09 at 22 48 42](https://github.com/jilleb/mib1-toolbox/assets/162830186/7a9b3790-3fab-429c-ab03-1a2b03e020df)
![WhatsApp Image 2024-03-09 at 22 48 41 (2)](https://github.com/jilleb/mib1-toolbox/assets/162830186/63289568-4f6c-4247-9e41-88be065a4ea0)
![WhatsApp Image 2024-03-09 at 22 48 41 (1)](https://github.com/jilleb/mib1-toolbox/assets/162830186/e462ac04-5e16-4ddc-8d6f-a1ccdfd5e0bb)
![WhatsApp Image 2024-03-09 at 22 48 41](https://github.com/jilleb/mib1-toolbox/assets/162830186/2d6f67b9-7648-46b8-8620-166f6d33759a)

**Comment by jilleb** [comment]
Wrong GitHub repository 😏
